# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/proto/grpcintegration/EventNotificationProto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobuf.proto.net.packet import PacketContextProto_pb2 as protobuf_dot_proto_dot_net_dot_packet_dot_PacketContextProto__pb2
from protobuf.proto.net.link import LinkEventProto_pb2 as protobuf_dot_proto_dot_net_dot_link_dot_LinkEventProto__pb2
from protobuf.proto.protocols.openflow import OpenFlowPacketContextProto_pb2 as protobuf_dot_proto_dot_protocols_dot_openflow_dot_OpenFlowPacketContextProto__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;protobuf/proto/grpcintegration/EventNotificationProto.proto\x12\x0fgrpcintegration\x1a\x32protobuf/proto/net/packet/PacketContextProto.proto\x1a,protobuf/proto/net/link/LinkEventProto.proto\x1a\x42protobuf/proto/protocols/openflow/OpenFlowPacketContextProto.proto\"1\n\x13RegistrationRequest\x12\x1a\n\x08\x63lientId\x18\x01 \x01(\tR\x08\x63lientId\"N\n\x14RegistrationResponse\x12\x1a\n\x08\x63lientId\x18\x01 \x01(\tR\x08\x63lientId\x12\x1a\n\x08serverId\x18\x02 \x01(\tR\x08serverId\"S\n\x05Topic\x12\x1a\n\x08\x63lientId\x18\x01 \x01(\tR\x08\x63lientId\x12.\n\x04type\x18\x02 \x01(\x0e\x32\x1a.grpcintegration.topicTypeR\x04type\"\xf0\x02\n\x0cNotification\x12\x1a\n\x08\x63lientId\x18\x01 \x01(\tR\x08\x63lientId\x12\x1a\n\x08serverId\x18\x02 \x01(\tR\x08serverId\x12.\n\x04type\x18\x03 \x01(\x0e\x32\x1a.grpcintegration.topicTypeR\x04type\x12\x46\n\rpacketContext\x18\x04 \x01(\x0b\x32\x1e.net.packet.PacketContextProtoH\x00R\rpacketContext\x12?\n\tlinkEvent\x18\x05 \x01(\x0b\x32\x1f.net.link.LinkNotificationProtoH\x00R\tlinkEvent\x12\x66\n\x15openFlowPacketContext\x18\x06 \x01(\x0b\x32..protocols.openflow.OpenFlowPacketContextProtoH\x00R\x15openFlowPacketContextB\x07\n\x05\x65vent*F\n\ttopicType\x12\x10\n\x0cPACKET_EVENT\x10\x00\x12\x0e\n\nLINK_EVENT\x10\x01\x12\x17\n\x13OPENFLOW_PACKET_CTX\x10\x02\x42-\n+org.onosproject.grpc.grpcintegration.modelsb\x06proto3')

_TOPICTYPE = DESCRIPTOR.enum_types_by_name['topicType']
topicType = enum_type_wrapper.EnumTypeWrapper(_TOPICTYPE)
PACKET_EVENT = 0
LINK_EVENT = 1
OPENFLOW_PACKET_CTX = 2


_REGISTRATIONREQUEST = DESCRIPTOR.message_types_by_name['RegistrationRequest']
_REGISTRATIONRESPONSE = DESCRIPTOR.message_types_by_name['RegistrationResponse']
_TOPIC = DESCRIPTOR.message_types_by_name['Topic']
_NOTIFICATION = DESCRIPTOR.message_types_by_name['Notification']
RegistrationRequest = _reflection.GeneratedProtocolMessageType('RegistrationRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTRATIONREQUEST,
  '__module__' : 'protobuf.proto.grpcintegration.EventNotificationProto_pb2'
  # @@protoc_insertion_point(class_scope:grpcintegration.RegistrationRequest)
  })
_sym_db.RegisterMessage(RegistrationRequest)

RegistrationResponse = _reflection.GeneratedProtocolMessageType('RegistrationResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTRATIONRESPONSE,
  '__module__' : 'protobuf.proto.grpcintegration.EventNotificationProto_pb2'
  # @@protoc_insertion_point(class_scope:grpcintegration.RegistrationResponse)
  })
_sym_db.RegisterMessage(RegistrationResponse)

Topic = _reflection.GeneratedProtocolMessageType('Topic', (_message.Message,), {
  'DESCRIPTOR' : _TOPIC,
  '__module__' : 'protobuf.proto.grpcintegration.EventNotificationProto_pb2'
  # @@protoc_insertion_point(class_scope:grpcintegration.Topic)
  })
_sym_db.RegisterMessage(Topic)

Notification = _reflection.GeneratedProtocolMessageType('Notification', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATION,
  '__module__' : 'protobuf.proto.grpcintegration.EventNotificationProto_pb2'
  # @@protoc_insertion_point(class_scope:grpcintegration.Notification)
  })
_sym_db.RegisterMessage(Notification)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n+org.onosproject.grpc.grpcintegration.models'
  _TOPICTYPE._serialized_start=833
  _TOPICTYPE._serialized_end=903
  _REGISTRATIONREQUEST._serialized_start=246
  _REGISTRATIONREQUEST._serialized_end=295
  _REGISTRATIONRESPONSE._serialized_start=297
  _REGISTRATIONRESPONSE._serialized_end=375
  _TOPIC._serialized_start=377
  _TOPIC._serialized_end=460
  _NOTIFICATION._serialized_start=463
  _NOTIFICATION._serialized_end=831
# @@protoc_insertion_point(module_scope)
